import { afterAll, beforeAll, describe, expect, it } from 'vitest'
import { Client } from 'pg'
import { randomUUID } from 'node:crypto'
import { mkdtemp, readFile, readdir, realpath, rm, stat, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { SqlService } from '../src/main/engines/sql'
import { NativeBackupService } from '../src/main/persistence/native-backup'
import { profileSchema } from '../src/shared/contracts'
import type { NativeBackupArchive, NativeBackupTool } from '../src/shared/native-backup'

describe.skipIf(process.env.HARBOR_NATIVE_BACKUP !== '1')(
  'real native PostgreSQL backup/restore drill',
  () => {
    const suffix = randomUUID().replaceAll('-', '').slice(0, 12),
      database = `backup_source_${suffix}`,
      restored = `backup_restored_${suffix}`,
      failedTarget = `backup_failed_${suffix}`,
      cancelledTarget = `backup_cancelled_${suffix}`,
      role = `backup_role_${suffix}`
    const port = Number(process.env.HARBOR_BACKUP_PG_PORT || 15434),
      options = { host: '127.0.0.1', port, user: 'harbor', password: 'harbor_test' }
    const admin = new Client({ ...options, database: 'harbor' }),
      source = new Client({ ...options, database })
    const profile = profileSchema.parse({
      id: randomUUID(),
      name: 'Disposable native backup fixture',
      engine: 'postgres',
      host: options.host,
      port,
      username: options.user,
      database,
      readOnly: false,
    })
    const native = new SqlService()
    let service: NativeBackupService,
      directory: string,
      dump: NativeBackupTool,
      restore: NativeBackupTool,
      archive: NativeBackupArchive
    const wait = async (id: string) => {
      await expect.poll(() => service.getJob(id).state, { timeout: 30000, interval: 50 }).not.toBe('running')
      return service.getJob(id)
    }
    beforeAll(async () => {
      directory = await realpath(await mkdtemp(join(tmpdir(), 'harbor-native-backup-test-')))
      await admin.connect()
      expect(
        Number((await admin.query('SHOW server_version_num')).rows[0].server_version_num),
      ).toBeGreaterThanOrEqual(180000)
      await admin.query(`CREATE DATABASE "${database}" TEMPLATE template0`)
      await source.connect()
      await source.query(
        "CREATE TYPE public.mood AS ENUM('calm','busy'); CREATE TABLE public.parent(id bigint PRIMARY KEY,label text); CREATE TABLE public.records(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,parent_id bigint REFERENCES public.parent(id),amount numeric(30,8),bytes bytea,mood public.mood); CREATE INDEX amount_index ON public.records(amount); CREATE VIEW public.record_view AS SELECT id,amount FROM public.records; CREATE FUNCTION public.double_value(integer) RETURNS integer LANGUAGE sql IMMUTABLE AS 'SELECT $1 * 2'; INSERT INTO public.parent VALUES(9007199254740993,'precise'); INSERT INTO public.records(parent_id,amount,bytes,mood) VALUES(9007199254740993,12345678901234567890.12345678,decode('00ff0102','hex'),'calm');",
      )
      expect(await native.connect(profile, { password: options.password })).toMatchObject({
        state: 'connected',
      })
      service = new NativeBackupService({
        profile: () => profile,
        secrets: () => ({ password: options.password }),
        execute: (input) => native.execute(input),
        closeSession: (input) => native.closeSession(input),
        cancel: (input) => native.cancel(input),
        temporaryDirectory: join(directory, 'private'),
      })
      dump = await service.chooseTool(process.env.HARBOR_PG_DUMP || '/opt/homebrew/bin/pg_dump', 'pg_dump')
      restore = await service.chooseTool(
        process.env.HARBOR_PG_RESTORE || '/opt/homebrew/bin/pg_restore',
        'pg_restore',
      )
    }, 30000)
    afterAll(async () => {
      await service?.closeAll()
      await native.closeAll()
      await source.end()
      for (const name of [restored, failedTarget, cancelledTarget, database])
        await admin.query(`DROP DATABASE IF EXISTS "${name}" WITH (FORCE)`).catch(() => undefined)
      await admin.query(`DROP ROLE IF EXISTS "${role}"`).catch(() => undefined)
      await admin.end()
      if (directory) await rm(directory, { recursive: true, force: true })
    })
    it('writes a private custom archive without overwriting and restores representative native contents into a reviewed new database', async () => {
      const preview = await service.preview({
        mode: 'backup',
        connectionId: profile.id,
        toolId: dump.id,
        maxBytes: 1024 ** 3,
        maxDurationSeconds: 30,
      })
      expect(preview.blockedReasons, JSON.stringify(preview)).toEqual([])
      expect(service.previewMode(preview.token)).toBe('backup')
      await expect(
        service.start({ token: preview.token, confirm: 'wrong' }, join(directory, 'data.dump')),
      ).rejects.toThrow(/exact target/)
      const job = await service.start(
          { token: preview.token, confirm: preview.confirmation },
          join(directory, 'data.dump'),
        ),
        completed = await wait(job.id)
      expect(completed.state, JSON.stringify(completed)).toBe('completed')
      expect(completed.bytes).toBeGreaterThan(20)
      expect(completed.sha256).toMatch(/^[a-f0-9]{64}$/)
      expect((await stat(completed.outputPath!)).mode & 0o777).toBe(0o600)
      expect(await readdir(join(directory, 'private'))).toEqual([])
      archive = await service.chooseArchive(completed.outputPath!)
      const restorePreview = await service.preview({
        mode: 'restore',
        connectionId: profile.id,
        toolId: restore.id,
        archiveId: archive.id,
        newDatabase: restored,
        trustArchive: true,
        maxDurationSeconds: 30,
      })
      expect(restorePreview.blockedReasons, JSON.stringify(restorePreview)).toEqual([])
      expect(restorePreview.archiveSummary!.entries).toBeGreaterThan(5)
      expect((await admin.query('SELECT oid FROM pg_database WHERE datname=$1', [restored])).rowCount).toBe(0)
      const restoreJob = await service.start({
          token: restorePreview.token,
          confirm: restorePreview.confirmation,
        }),
        restoredJob = await wait(restoreJob.id)
      expect(restoredJob.state, JSON.stringify(restoredJob)).toBe('completed')
      expect(restoredJob.verification).toMatchObject({ tables: 2, views: 1, indexes: 3 })
      const destination = new Client({ ...options, database: restored })
      await destination.connect()
      try {
        expect(
          (
            await destination.query(
              "SELECT parent_id,amount,encode(bytes,'hex') AS bytes,mood FROM public.records",
            )
          ).rows,
        ).toEqual([
          {
            parent_id: '9007199254740993',
            amount: '12345678901234567890.12345678',
            bytes: '00ff0102',
            mood: 'calm',
          },
        ])
        expect((await destination.query('SELECT public.double_value(4) AS value')).rows[0].value).toBe(8)
        await expect(destination.query('INSERT INTO public.records(parent_id) VALUES(123)')).rejects.toThrow(
          /foreign key/,
        )
        expect(
          (
            await destination.query(
              'INSERT INTO public.records(parent_id) VALUES(9007199254740993) RETURNING id',
            )
          ).rows[0].id,
        ).toBe('3')
      } finally {
        await destination.end()
      }
      await expect(
        service.start({ token: restorePreview.token, confirm: restorePreview.confirmation }),
      ).rejects.toThrow(/expired/)
      expect(JSON.stringify(restoredJob)).not.toContain(options.password)
    }, 60000)
    it('rejects an existing database, an existing output file and changed archive identity without overwriting either', async () => {
      const duplicate = await service.preview({
        mode: 'restore',
        connectionId: profile.id,
        toolId: restore.id,
        archiveId: archive.id,
        newDatabase: restored,
        trustArchive: true,
        maxDurationSeconds: 30,
      })
      expect(duplicate.blockedReasons.join(' ')).toMatch(/already exists/)
      const path = join(directory, 'preserve.dump')
      await writeFile(path, 'pre-existing user bytes')
      const preview = await service.preview({
        mode: 'backup',
        connectionId: profile.id,
        toolId: dump.id,
        maxBytes: 1024 ** 3,
        maxDurationSeconds: 30,
      })
      const job = await service.start({ token: preview.token, confirm: preview.confirmation }, path)
      expect((await wait(job.id)).state).toBe('failed')
      expect(await readFile(path, 'utf8')).toBe('pre-existing user bytes')
      const mutable = join(directory, 'changed.dump')
      await writeFile(mutable, await readFile(archive.path))
      const selected = await service.chooseArchive(mutable)
      await writeFile(mutable, 'PGDMP changed after selection')
      const changed = await service.preview({
        mode: 'restore',
        connectionId: profile.id,
        toolId: restore.id,
        archiveId: selected.id,
        newDatabase: `backup_changed_${suffix}`,
        trustArchive: true,
        maxDurationSeconds: 30,
      })
      expect(changed.blockedReasons.join(' ')).toMatch(/changed/)
    })
    it('cancels a native dump blocked by a real table lock and cleans credential and partial files', async () => {
      await source.query('BEGIN; LOCK TABLE public.records IN ACCESS EXCLUSIVE MODE')
      try {
        const preview = await service.preview({
          mode: 'backup',
          connectionId: profile.id,
          toolId: dump.id,
          maxBytes: 1024 ** 3,
          maxDurationSeconds: 30,
        })
        const output = join(directory, 'cancelled.dump'),
          job = await service.start({ token: preview.token, confirm: preview.confirmation }, output)
        await expect.poll(() => service.getJob(job.id).details.length, { timeout: 10000 }).toBeGreaterThan(0)
        service.cancelJob(job.id)
        const result = await wait(job.id)
        expect(result.state, JSON.stringify(result)).toBe('cancelled')
        await expect(stat(output)).rejects.toThrow(/ENOENT/)
        expect(await readdir(join(directory, 'private'))).toEqual([])
        expect((await readdir(directory)).some((name) => name.includes('.partial'))).toBe(false)
      } finally {
        await source.query('ROLLBACK')
      }
    })
    it('retains a new failed restore target and reports uncertainty without automatically dropping or retrying it', async () => {
      await admin.query(`CREATE ROLE "${role}" NOLOGIN`)
      await source.query(`CREATE POLICY native_restore_policy ON public.records TO "${role}" USING(true)`)
      const preview = await service.preview({
        mode: 'backup',
        connectionId: profile.id,
        toolId: dump.id,
        maxBytes: 1024 ** 3,
        maxDurationSeconds: 30,
      })
      const dumped = await wait(
        (
          await service.start(
            { token: preview.token, confirm: preview.confirmation },
            join(directory, 'policy.dump'),
          )
        ).id,
      )
      expect(dumped.state, JSON.stringify(dumped)).toBe('completed')
      await source.query('DROP POLICY native_restore_policy ON public.records')
      await admin.query(`DROP ROLE "${role}"`)
      const selected = await service.chooseArchive(dumped.outputPath!)
      const review = await service.preview({
        mode: 'restore',
        connectionId: profile.id,
        toolId: restore.id,
        archiveId: selected.id,
        newDatabase: failedTarget,
        trustArchive: true,
        maxDurationSeconds: 30,
      })
      expect(review.blockedReasons).toEqual([])
      const result = await wait(
        (await service.start({ token: review.token, confirm: review.confirmation })).id,
      )
      expect(result.state, JSON.stringify(result)).toBe('unknown')
      expect(result.warnings.join(' ')).toMatch(/does not exist/)
      expect(
        (await admin.query('SELECT oid FROM pg_database WHERE datname=$1', [failedTarget])).rowCount,
      ).toBe(1)
      const target = new Client({ ...options, database: failedTarget })
      await target.connect()
      try {
        expect(
          (await target.query("SELECT count(*)::integer AS count FROM pg_tables WHERE schemaname='public'"))
            .rows[0].count,
        ).toBe(0)
      } finally {
        await target.end()
      }
      expect(await readdir(join(directory, 'private'))).toEqual([])
    }, 30000)
    it('invalidates a review on profile change/disconnect and refuses mismatched native tool kinds', async () => {
      const input = {
        mode: 'backup' as const,
        connectionId: profile.id,
        toolId: dump.id,
        maxBytes: 16 * 1024 ** 2,
        maxDurationSeconds: 30,
      }
      await expect(service.preview({ ...input, toolId: restore.id })).rejects.toThrow(/matching/)
      const preview = await service.preview(input),
        name = profile.name
      try {
        profile.name = 'Changed after review'
        await expect(
          service.start(
            { token: preview.token, confirm: preview.confirmation },
            join(directory, 'changed-profile.dump'),
          ),
        ).rejects.toThrow(/profile changed/)
      } finally {
        profile.name = name
      }
      const fresh = await service.preview(input)
      await service.cancelForConnection(profile.id)
      await expect(
        service.start(
          { token: fresh.token, confirm: fresh.confirmation },
          join(directory, 'disconnected.dump'),
        ),
      ).rejects.toThrow(/expired/)
      await expect(stat(join(directory, 'changed-profile.dump'))).rejects.toThrow(/ENOENT/)
      await expect(stat(join(directory, 'disconnected.dump'))).rejects.toThrow(/ENOENT/)
    })
    it('blocks an older native tool than the reported server version (version-policy fault injection)', async () => {
      const versionCheck = new NativeBackupService({
        profile: () => profile,
        secrets: () => ({ password: options.password }),
        closeSession: (input) => native.closeSession(input),
        execute: async (input) => {
          const result = await native.execute(input)
          if (input.sql.includes('server_version_num'))
            for (const set of result.sets)
              for (const row of set.rows) {
                row[set.columns.findIndex((column) => column.name === 'version_number')] = '990000'
                row[set.columns.findIndex((column) => column.name === 'version')] = '99.0 policy fixture'
              }
          return result
        },
      })
      try {
        const tool = await versionCheck.chooseTool(dump.path, 'pg_dump')
        const review = await versionCheck.preview({
          mode: 'backup',
          connectionId: profile.id,
          toolId: tool.id,
          maxBytes: 16 * 1024 ** 2,
          maxDurationSeconds: 30,
        })
        expect(review.blockedReasons.join(' ')).toMatch(/at least as new/)
        await expect(
          versionCheck.start(
            { token: review.token, confirm: review.confirmation },
            join(directory, 'unsupported-version.dump'),
          ),
        ).rejects.toThrow(/expired/)
      } finally {
        await versionCheck.closeAll()
      }
    })
    it('cancels a real restore while building an index, retains its new target and cleans native resources', async () => {
      await source.query(
        'CREATE TABLE cancel_fixture AS SELECT n FROM generate_series(1,80) n; CREATE FUNCTION slow_index(integer) RETURNS integer LANGUAGE plpgsql IMMUTABLE AS $$ BEGIN PERFORM pg_sleep(0.02); RETURN $1; END $$; CREATE INDEX cancel_slow_index ON cancel_fixture(slow_index(n))',
      )
      const review = await service.preview({
        mode: 'backup',
        connectionId: profile.id,
        toolId: dump.id,
        maxBytes: 16 * 1024 ** 2,
        maxDurationSeconds: 30,
      })
      const dumped = await wait(
        (
          await service.start(
            { token: review.token, confirm: review.confirmation },
            join(directory, 'cancel-restore.dump'),
          )
        ).id,
      )
      expect(dumped.state).toBe('completed')
      const selected = await service.chooseArchive(dumped.outputPath!)
      const restoreReview = await service.preview({
        mode: 'restore',
        connectionId: profile.id,
        toolId: restore.id,
        archiveId: selected.id,
        newDatabase: cancelledTarget,
        trustArchive: true,
        maxDurationSeconds: 30,
      })
      expect(restoreReview.blockedReasons).toEqual([])
      const job = await service.start({ token: restoreReview.token, confirm: restoreReview.confirmation })
      await expect
        .poll(
          async () =>
            (
              await admin.query(
                "SELECT count(*)::integer AS count FROM pg_stat_activity WHERE application_name=$1 AND state='active' AND query LIKE '%CREATE INDEX%cancel_slow_index%'",
                [`harbor-native-${job.id}`],
              )
            ).rows[0].count,
          { timeout: 10000, interval: 20 },
        )
        .toBe(1)
      service.cancelJob(job.id)
      const result = await wait(job.id)
      expect(result.state).toBe('unknown')
      expect(result.message).toContain('retained for inspection')
      await expect
        .poll(
          async () =>
            (
              await admin.query(
                'SELECT count(*)::integer AS count FROM pg_stat_activity WHERE application_name=$1',
                [`harbor-native-${job.id}`],
              )
            ).rows[0].count,
        )
        .toBe(0)
      expect(
        (await admin.query('SELECT oid FROM pg_database WHERE datname=$1', [cancelledTarget])).rowCount,
      ).toBe(1)
      const target = new Client({ ...options, database: cancelledTarget })
      await target.connect()
      try {
        expect(
          (await target.query("SELECT count(*)::integer AS count FROM pg_tables WHERE schemaname='public'"))
            .rows[0].count,
        ).toBe(0)
      } finally {
        await target.end()
      }
      expect(await readdir(join(directory, 'private'))).toEqual([])
    })
  },
)
