import { createHash } from 'node:crypto'
import { createRequire } from 'node:module'
import { mkdtempSync, readFileSync, realpathSync, rmSync, statSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { dirname, join, resolve } from 'node:path'
import { spawnSync } from 'node:child_process'
import { fileURLToPath } from 'node:url'

const root = realpathSync(resolve(dirname(fileURLToPath(import.meta.url)), '..'))
const require = createRequire(import.meta.url)

export function sandboxPolicy(projectRoot, electronBinary) {
  const paths = [electronBinary, join(projectRoot, 'release/linux-unpacked/harbor-db')]
  for (const path of paths) {
    // Reject AppArmor pattern syntax: these grants must match exactly two executables.
    if (/[\x00-\x1f"\\*?{}\[\]^]/.test(path))
      throw new Error('The workspace path contains characters unsupported by this AppArmor setup.')
  }
  const id = createHash('sha256').update(projectRoot).digest('hex').slice(0, 12)
  return {
    filename: `harbor-db-${id}`,
    text: `# Harbor DB: sandbox namespace permission for this workspace only.\n# Generated by scripts/linux-sandbox.mjs; no system-wide setting changes.\nabi <abi/4.0>,\ninclude <tunables/global>\n\n${paths.map((path, index) => `profile harbor-db-${id}-${index ? 'package' : 'dev'} "${path}" flags=(unconfined) {\n  userns,\n}`).join('\n\n')}\n`,
  }
}

function run(command, args, options = {}) {
  const result = spawnSync(command, args, { stdio: 'inherit', ...options })
  if (result.error) throw result.error
  if (result.status !== 0) throw new Error(`${command} did not complete successfully.`)
}

function check(electronBinary) {
  let restricted = false
  try {
    restricted = readFileSync('/proc/sys/kernel/apparmor_restrict_unprivileged_userns', 'utf8').trim() === '1'
  } catch {
    /* This restriction is specific to some Linux distributions. */
  }
  if (!restricted) return
  try {
    const helper = statSync(join(dirname(electronBinary), 'chrome-sandbox'))
    if (helper.uid === 0 && (helper.mode & 0o7777) === 0o4755) return
  } catch {
    /* Check the unprivileged namespace route instead. */
  }

  // Probe through the actual Electron executable so its own AppArmor attachment applies.
  // Running `unshare` directly from this script would incorrectly reject an installed rule.
  const probe = spawnSync(
    electronBinary,
    [
      '-e',
      `
    const { spawnSync } = require('node:child_process');
    const result = spawnSync('unshare', ['--user', '--map-root-user', 'true']);
    process.exit(result.status === 0 ? 0 : 1);
  `,
    ],
    {
      env: { ...process.env, ELECTRON_RUN_AS_NODE: '1' },
      stdio: 'ignore',
      timeout: 5000,
    },
  )
  if (probe.status === 0) return
  throw new Error(
    'Ubuntu is blocking Electron’s sandbox namespaces in this launch context.\n' +
      'Run `npm run setup:linux` once, then retry this command.\n' +
      'Setup installs a rule for this workspace’s Electron and packaged Harbor DB executables.\n' +
      'It requires sudo to write /etc/apparmor.d and load the rule; the app itself runs as your user.',
  )
}

function setup(policy) {
  const directory = mkdtempSync(join(tmpdir(), 'harbor-apparmor-'))
  const temporary = join(directory, policy.filename)
  const installed = join('/etc/apparmor.d', policy.filename)
  try {
    writeFileSync(temporary, policy.text, { mode: 0o600 })
    run('/usr/sbin/apparmor_parser', ['--skip-kernel-load', '--skip-cache', temporary])
    console.log(`Installing ${installed}\n\n${policy.text}`)
    console.log('Administrator authentication is needed only to install and load this per-app rule.')
    run('/usr/bin/sudo', [
      '/usr/bin/install',
      '-o',
      'root',
      '-g',
      'root',
      '-m',
      '644',
      '--',
      temporary,
      installed,
    ])
    run('/usr/bin/sudo', ['/usr/sbin/apparmor_parser', '--replace', '--skip-cache', installed])
    console.log('Harbor DB sandbox setup complete. Run `npm run dev` or launch the packaged application.')
  } finally {
    rmSync(directory, { recursive: true, force: true })
  }
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  try {
    const action = process.argv[2] || 'check'
    if (process.platform !== 'linux') {
      if (action !== 'check') console.log('This sandbox setup is only needed on affected Linux systems.')
    } else {
      const electronBinary = realpathSync(require('electron'))
      if (action === 'check') check(electronBinary)
      else if (action === 'print') console.log(sandboxPolicy(root, electronBinary).text)
      else if (action === 'setup') setup(sandboxPolicy(root, electronBinary))
      else throw new Error('Expected check, print, or setup.')
    }
  } catch (error) {
    console.error(`Harbor DB: ${error.message}`)
    process.exitCode = 1
  }
}
